"""initial migrate for service table

Revision ID: 622e396ffa5b
Revises: 64bb574596c2
Create Date: 2025-11-06 12:21:00.227476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622e396ffa5b'
down_revision = '64bb574596c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
